# Generated by Django 5.0.1 on 2024-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Product name')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=100, verbose_name='Product details')),
                ('cat', models.IntegerField(choices=[(1, 'Clothes'), (2, 'Books'), (3, 'Stationary'), (4, 'Electronics')], verbose_name='category')),
                ('is_active', models.BooleanField(default=True, verbose_name='available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
